spring:
  datasource:
    url: jdbc:mysql://192.168.246.128:3306/online_judge?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: hejianglll
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
  redis:
    port: 6379
    host: db.boxjan.li
    password: redis-db.boxjan.li
  mail:
    host: smtp.bestsort.show
    port: 25
    username: oj@bestsort.show
    password: eaNWSsJTHqb9l5kU
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: create

  proxy:
    trusts: "127.0.0.1/8,::1/128"
logging:
  path:
online-judge:
  cache-store-type: REDIS
  debug:
    generator-data: false
    refresh-all-problem-solution-count: false
    refresh-rank-list: false